# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-10 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_auto_20200608_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('about', models.TextField(max_length=5000)),
                ('organiser_id', models.IntegerField(max_length=255)),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
