# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-10 19:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_auto_20200610_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventprofile',
            name='organiser_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
