# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-10 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_auto_20200610_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventprofile',
            old_name='organiser_id',
            new_name='user_profile',
        ),
    ]
