# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-11 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0006_auto_20200610_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventprofile',
            name='user_profile',
        ),
    ]
