# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-13 05:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0007_remove_eventprofile_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventprofile',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
